config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'file_stats#index'

  if Rails.env.development?
    mount Sidekiq::Web => '/sidekiq'
  end
  
  resources :file_stats

  put '/file_stats/:id/pause', to: "file_stats#pause", as: 'pause_file_stat'
  put '/file_stats/:id/unpause', to: "file_stats#unpause", as: 'unpause_file_stat'
  put '/file_stats/:id/cancel', to: "file_stats#cancel", as: 'cancel_file_stat'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/file_stat.rb
class FileStat
  include Mongoid::Document
  include FileStatsHelper

#  field :username, type: String, default: get_current_user()
  field :username, type: String, default: "Eric"
  field :filename, type: String
  field :job_id, type: String
  field :status, type: String, default: "Queued"
  field :status_message, type: String, default: ""
  field :progress, type: String, default: ""
end

app/controllers/file_stats_controller.rb
class FileStatsController < ApplicationController
  include FileStatsHelper

  before_action :set_file_stat, only: [:show, :edit, :update, :destroy, :pause, :unpause, :cancel]

  def pause
    @file_stat = FileStat.find(params[:id])
    helpers.pause_job(@file_stat.job_id)
    redirect_back(fallback_location: root_path)
  end

  def unpause
    @file_stat = FileStat.find(params[:id])
    helpers.unpause_job(@file_stat.job_id)
    redirect_back(fallback_location: root_path)
  end

  def cancel
    @file_stat = FileStat.find(params[:id])
    helpers.cancel_job(@file_stat.job_id)
    redirect_back(fallback_location: root_path)
  end

  # GET /file_stats
  # GET /file_stats.json
  def index
    @file_stats = FileStat.all
  end

  # GET /file_stats/1
  # GET /file_stats/1.json
  def show
  end

  # GET /file_stats/new
  def new
    @file_stat = FileStat.new
  end

  # GET /file_stats/1/edit
  def edit
  end

  # POST /file_stats
  # POST /file_stats.json
  def create
    @file_stat = FileStat.new(file_stat_params)
    
    logger.debug(file_stat_params)

    respond_to do |format|
      if @file_stat.save

        logger.debug("Starting sidekiq process for file #{@file_stat.filename} database id #{@file_stat.id}")
        jid = FileStatsWorker.perform_async(@file_stat.filename, @file_stat._id.to_s()) 
        
        @file_stat.job_id = jid
        @file_stat.save

        format.html { redirect_to @file_stat, notice: 'File stat was successfully created.' }
        format.json { render :show, status: :created, location: @file_stat }
      else
        format.html { render :new }
        format.json { render json: @file_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /file_stats/1
  # PATCH/PUT /file_stats/1.json
  def update
    respond_to do |format|
      if @file_stat.update(file_stat_params)
        format.html { redirect_to @file_stat, notice: 'File stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @file_stat }
      else
        format.html { render :edit }
        format.json { render json: @file_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /file_stats/1
  # DELETE /file_stats/1.json
  def destroy
    if @file_stat.status != 'Finished'
      delete_job(@file_stat.job_id)
    end
    # 
    delete_results(@file_stat._id.to_s())

    @file_stat.destroy
    respond_to do |format|
      format.html { redirect_to file_stats_url, notice: 'File stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_file_stat
      @file_stat = FileStat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def file_stat_params
      params.require(:file_stat).permit(:username, :filename, :job_id, :status, :status_message, :progress)
    end

end

app/helpers/file_stats_helper.rb
require 'sidekiq/api'

module FileStatsHelper
 
  class CancelledException < StandardError
  end

  # stub for integration with authentication
  def get_current_user()  
    return "user@email.com"
  end

  # name of the queue
  def get_queue_name()
    'file_stats'
  end

  # TODO: check present in init?
  def get_results_base_dir()
    return ENV["FILE_STATS_RESULTS_BASE_DIR"] || '/tmp/file_stats/results/'
  end

  # where the results files are to be stored
  def get_results_dir(db_id)
    dir = "#{get_results_base_dir()}#{db_id}/"
    return dir
  end
  
  # delete the directory containing the results
  # can be called even if the results haven't been written
  def delete_results(db_id)
    dir = "#{get_results_base_dir()}#{db_id}/"
    FileUtils.rm_rf(dir)
  end

  # delete the job from any Sidekiq queues
  # call cancel_job in case the job is being processed
  def delete_job(job_id)

    Sidekiq::Queue.new(get_queue_name()).select do |job|
      job.delete if job.jid == job_id
    end

    Sidekiq::ScheduledSet.new.select do |job|
      job.delete if job.jid == job_id
    end
  
    Sidekiq::RetrySet.new.select do |job|
      job.delete if job.jid == job_id
    end
  
    Sidekiq::DeadSet.new.select do |job|
      job.delete if job.jid == job_id
    end
  
    cancel_job(job_id)

  end

  # to report how many jobs are queued
  def get_queue_length()
    return(Sidekiq::Queue.new("file_stats").size)
  end

  # to report how many jobs are running
  def get_running_jobs()
    running = 0
    Sidekiq::ProcessSet.new.each do |process|
      running += process['busy']   
    end
    return(running)
  end    

  # set / test a pause semaphore
  def pause_job(job_id)
    Sidekiq.redis {|c| c.setex("pause-#{job_id}", 86400, 1) }
  end

  def unpause_job(job_id)
    Sidekiq.redis {|c| c.del("pause-#{job_id}", 86400, 1) }
  end

  def is_job_paused?(job_id)
    x = Sidekiq.redis {|c| c.exists?("pause-#{job_id}") }
    return x
  end

  # set / test a cancel semaphore
  # 10 minute timeout should be plenty and won't clutter up Redis if
  # it's not deleted'
  def cancel_job(job_id)
    x = Sidekiq.redis {|c| c.setex("cancel-#{job_id}", 600, 1) }   
    return x
  end

  def is_job_cancelled?(job_id)
    x = Sidekiq.redis {|c| c.exists?("cancel-#{job_id}") }
    return x
  end

  # check whether processing should be cancelled
  def check_cancelled(file_stat)
    if is_job_cancelled?(file_stat.job_id)
      raise CancelledException.new, 'Cancelled'
    end
  end

  # check whether processing should be paused and 
  # sit in a sleep loop until unpaused
  def check_paused(file_stat)
    if file_stat.job_id.length() < 6
      raise "Bad Job ID in check_paused()"
    end
    if !is_job_paused?(file_stat.job_id)
      return
    end
    prev_progress = file_stat.progress
    file_stat.update(progress: 'Paused')
    loop do
      check_cancelled(file_stat)  # job can be cancelled while paused
      sleep 5
      break if !is_job_paused?(file_stat.job_id)
    end 
    file_stat.update(progress: prev_progress)
  end

  # maybe better done better through Redis or possibly actionCable
  def update_progress(progress, file_stat)
    logger.debug("Setting Progress #{progress} for ID #{file_stat._id}")
    file_stat.update(progress: progress)
  end

  def process_file(filename, db_id)
    file_stat = nil
    begin
      begin
        file_stat = FileStat.find(db_id)
      rescue
        throw "Failed to find record for FileStat #{db_id}"
      end
      file_stat.update(status: 'Processing', status_message: '')

      if Rails.env.development? && filename == "throw"          # for testing error handling
        throw "forced error"
      elsif Rails.env.development? && filename[0,5] == "sleep"  # simulate processing a file without high system load
        len = 10*60 # default sleep length
        s = filename.split(' ')
        if s.size > 1
          logger.debug "sleeping for " + s[1] + "seconds"
          len = s[1].to_i()
        else
          logger.debug "sleeping for ten minutes"
        end
        (1..len).step(5) do |i|
          check_cancelled(file_stat)
          check_paused(file_stat)
          #logger.debug "sleep step #{i} of #{len}"
          update_progress("#{(((i * 100.0) / len) + 0.5).to_i()}%", file_stat)
          sleep(5)
        end
        update_progress("", file_stat)
      else                            # process a file
        words = Hash.new(0) # for most and least popular words
        pali = Hash.new(0) # for palindromic words
        flen = File.size(filename)
        freq = [flen / 100, 1000].max # update every 1% progress or 1000 records whichever is the greater
        logger.debug "processing file: #{filename} length #{flen} freq #{freq}"
        charnum = 0
        # ToDo: 
        s = File.open(filename,'r') do |s|
          word = ''
          s.each_char do |chr|
            # check_cancelled and check_paused could be checked at a different frequency
            if charnum % freq == 0
              check_cancelled(file_stat)
              update_progress("#{(((charnum * 100.0) / flen) + 0.5).to_i()}%", file_stat)
              check_paused(file_stat)
            end
            charnum += 1
            c = chr.downcase
            o = c.ord
            if((o >= 97 && o <= 122) || (o >= 48 && o <= 57) || o == 45)  # check if number / letter / hyphen
              word.concat(c)
            else
              if word.size > 0
                words[word] += 1
                if word.size > 1 && word == word.reverse
                  pali[word] += 1
                end
                word = ''
              end
            end
          end
        end
        # write the result files
        FileUtils.mkdir_p(get_results_dir(db_id))
        # dump the top 10 words by frequency desc
        most = File.new(get_results_dir(db_id) + 'most.txt', 'w')
        n = 0
        words.sort_by{|k, v| -v}.each do |row|
          #logger.debug "#{row[0]} = #{row[1]}"
          most.write("#{row[0]},#{row[1]}\n")
          if (n += 1) >= 10
            break
          end
        end
        most.close()
        # dump all the words with the lowest frequency
        least = File.new(get_results_dir(db_id) + 'least.txt', 'w')
        min = -1
        words.sort_by{|k, v| v}.each do |row|
          if min == -1
            min = row[1]
          end
          if row[1] != min
            break
          end
          #logger.debug "#{row[0]} = #{row[1]}"
          least.write("#{row[0]},#{row[1]}\n")
        end
        least.close()
        # dump all the palindromes but sort desc
        palifile = File.new(get_results_dir(db_id) + 'palindromes.txt', 'w')
        pali.sort_by{|k, v| -v}.each do |row|
          #logger.debug "#{row[0]} = #{row[1]}"
          palifile.write("#{row[0]},#{row[1]}\n")
        end
        palifile.close()
        update_progress("", file_stat)
      end
    rescue CancelledException => c
      file_stat.update(status: 'Cancelled', status_message: '')
      delete_results(db_id)
      return true 
    rescue StandardError => e
      file_stat.update(status: 'Processing error', status_message: e.message)
      raise
    end
    file_stat.update(status: 'Processed', status_message: '')
    return true
  end

end

app/views/file_stats/_form.html.erb
<%= form_with(model: file_stat, local: true) do |form| %>
  <% if file_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(file_stat.errors.count, "error") %> prohibited this file_stat from being saved:</h2>

      <ul>
        <% file_stat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :filename %>
    <%= form.text_field :filename, autofocus: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/file_stats/edit.html.erb
<h1>Editing File Stat</h1>

<%= render 'form', file_stat: @file_stat %>

<%= link_to 'Show', @file_stat %> |
<%= link_to 'Back', file_stats_path %>

app/views/file_stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>File Statistics Calculator</h1>
<br>
<%= button_to 'Analyse a new file', new_file_stat_path, :method => "get" %>

<h3 class="js"># Queued analyses: <%= get_queue_length() %></h3>

<h3 class="js"># Running analyses: <%= get_running_jobs() %></h3>

<table id="file_list">
  <thead>
    <tr>
      <th>Filename</th>
      <th>Status</th>
      <th>Progress</th>
      <% if Rails.env.development? %>
        <th>db_id</th>
        <th>job_id</th>
      <% end %>
      <th colspan="4">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @file_stats.each do |file_stat| %>
      <tr>
        <td><%= file_stat.filename %></td>
        <td><%= file_stat.status %></td>
        <td><%= file_stat.progress %></td>
        <% if Rails.env.development? %>
          <td><%= file_stat._id.to_s() %></td>
          <td><%= file_stat.job_id %></td>
        <% end %>
        <td><%= link_to 'Show', file_stat %></td>
        <%  if file_stat.status == 'Processing' %>
        <%    if is_job_paused?(file_stat.job_id) %>
                <td><%= link_to 'Unpause', unpause_file_stat_path(file_stat), method: :put %></td>
        <%    else %>
                <td><%= link_to 'Pause', pause_file_stat_path(file_stat), method: :put %></td>
        <%    end %>
        <%  else %>
              <%# <td></td> %>
        <%  end %>
        <%  if file_stat.status == 'Processing' %>
              <td><%= link_to 'Cancel', cancel_file_stat_path(file_stat), method: :put %></td>
        <%  else %>
              <%# <td></td>  %>
        <%  end %>
        <td><%= link_to 'Delete', file_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<!--
<%= link_to 'New File Stat', new_file_stat_path %>
<br> -->

app/views/file_stats/new.html.erb
<h1>New File Stat</h1>

<%= render 'form', file_stat: @file_stat %>

<%= link_to 'Back', file_stats_path %>

app/views/file_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @file_stat.filename %>
</p>

<p>
  <strong>Status:</strong>
  <%= @file_stat.status %>
  <% if @file_stat.status == 'Processing' %>
    <br><strong>&nbsp;Progress:</strong>
    <%= @file_stat.progress %>
  <% end %>
  <% if @file_stat.status.downcase().include? 'error' %>
    <br><strong>&nbsp;Message:</strong>
    <%= @file_stat.status_message %>
  <% end %>
</p>

<%= button_to 'Back to analysis list', file_stats_path, :method => "get"  %>
<br>

<% if @file_stat.status == 'Processed' %>

  <h2>Results of analyses</h2>

  <h3>Top 10 most frequent words:</h3>
  <table id="result_list">
  <thead>
    <tr>
      <th>Word</th>
      <th>Frequency</th>
    </tr>
  </thead>

  <tbody>
    <% File.open("#{get_results_dir(@file_stat.id)}most.txt").each do |file_stat| %>
      <tr>
        <td><%= file_stat.split(',')[0] %></td> <td><%= file_stat.split(',')[1] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <h3>Palindromic words:</h3>
  <table id="result_list">
  <thead>
    <tr>
      <th>Word</th> <th>Frequency</th>
    </tr>
  </thead>

  <tbody>
    <% File.open("#{get_results_dir(@file_stat.id)}palindromes.txt").each do |file_stat| %>
      <tr>
        <td><%= file_stat.split(',')[0] %></td> <td><%= file_stat.split(',')[1] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Least frequent words:</h3>
  <table id="result_list">
  <thead>
    <tr>
      <th>Word</th> <th>Frequency</th>
    </tr>
  </thead>

  <tbody>
    <% File.open("#{get_results_dir(@file_stat.id)}least.txt").each do |file_stat| %>
      <tr>
        <td><%= file_stat.split(',')[0] %></td> <td><%= file_stat.split(',')[1] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% end %>